version: '3'

services:
    hub:
        image: esycat/jetbrains-hub
        container_name: jetbrains-hub
        restart: always
        environment:
            - VIRTUAL_HOST=hub.professionalconnection.biz
            - APP_PORT=80
        links:
            - database
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - hub-data:/var/lib/hub
            - hub-conf:/opt/hub/conf
        ulimits:
            memlock: -1
            nofile: 100000
            nproc: 32768      
    database:
        image: postgres:9.4
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
      volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
            
volumes:
    hub-data:
    hub-conf:
    upsource-data:
    upsource-conf:
    database-data:
