version: '3'

services:
    hub:
        image: esycat/jetbrains-hub
        container_name: jetbrains-hub
        restart: always
        environment:
            - VIRTUAL_HOST=${HUB_SUBDOMAIN:-hub}.${DOMAIN}
            - APP_PORT=443
            - VIRTUAL_PROTO=https
            - VIRTUAL_PORT=443
        links:
            - database
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - hub-data:/var/lib/hub
            - hub-conf:/opt/hub/conf
        ulimits:
            memlock: -1
            nofile: 100000
            nproc: 32768
        networks:
            - public
            
    youtrack:
        image: esycat/youtrack
        container_name: youtrack
        restart: always
        environment:
            - VIRTUAL_HOST=${YOUTRACK_SUBDOMAIN:-track}.${DOMAIN}
            - APP_PORT=80
        links:
            - database
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - youtrack-data:/var/lib/youtrack
            - youtrack-conf:/opt/youtrack/conf
        networks:
            - public
            
    upsource:
        image: esycat/upsource
        container_name: upsource
        restart: always
        environment:
            - VIRTUAL_HOST=${UPSOURCE_SUBDOMAIN:-source}.${DOMAIN}
            - APP_PORT=80
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - upsource-data:/var/lib/upsource
            - upsource-conf:/opt/upsource/conf
        ulimits:
            memlock: -1
            nofile: 100000
            nproc: 32768
        networks:
            - public
            
    database:
        image: postgres:9.4
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data
    nginx-proxy:
        image: eforce21/letsencrypt-nginx-proxy:1.0.2
        container_name: nginx-proxy
        restart: always   
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
        environment:
            - LETSENCRYPT_EMAIL=admin@professionalconnection.biz
        networks:
            - public
networks:
    public:
        external:
            name: public
    
volumes:
    hub-data:
    hub-conf:
    upsource-data:
    upsource-conf:
    youtrack-data:
    youtrack-conf:
    database-data:
